name: 'SMSChorinator'
version: 0.0.1
description: A web app built using Angular 2.
author: AlexNPavel <alexpavel123@gmail.com>
homepage: https://www.alexpavel.com

environment:
  sdk: '>=1.9.0 <2.0.0'

dependencies:
  angular2: ^2.0.0
  mongo_dart: ^0.2.10
  rpc: ^0.5.0

dev_dependencies:
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1

transformers:
- angular2:
    entry_points: web/main.dart
- dart_to_js_script_rewriter
